import Link from "next/link";

export const dynamic = "force-dynamic";

type WechatPayPageProps = {
  searchParams: Promise<{
    order?: string;
    code?: string;
  }>;
};

export default async function WechatPayPage({ searchParams }: WechatPayPageProps) {
  const params = await searchParams;
  const orderNo = params.order || "";
  const codeUrl = params.code || "";

  return (
    <main className="min-h-screen bg-slate-50 text-slate-950">
      <div className="mx-auto flex min-h-screen max-w-3xl flex-col items-center justify-center px-5 py-12">
        <div className="w-full rounded-3xl border border-slate-200 bg-white p-8 text-center shadow-xl">
          <p className="mx-auto mb-4 inline-flex rounded-full bg-cyan-50 px-4 py-2 text-sm font-semibold text-cyan-700">
            微信支付
          </p>
          <h1 className="text-3xl font-bold">请使用微信扫码完成支付</h1>
          {orderNo && (
            <p className="mt-3 break-all text-sm text-slate-500">订单号：{orderNo}</p>
          )}

          {codeUrl ? (
            <div className="mt-8 flex flex-col items-center gap-5">
              <div className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm">
                {/* eslint-disable-next-line @next/next/no-img-element -- QR code SVG is generated by our internal API route. */}
                <img
                  src={`/api/payments/qrcode?text=${encodeURIComponent(codeUrl)}`}
                  alt="微信支付二维码"
                  className="h-72 w-72"
                />
              </div>
              <p className="max-w-md text-sm leading-6 text-slate-500">
                支付成功后，系统会通过微信支付通知自动为你的账户增加点数。若页面未自动刷新，可稍后到“点数明细”或“我的订单”查看。
              </p>
            </div>
          ) : (
            <div className="mt-8 rounded-2xl border border-red-200 bg-red-50 px-5 py-4 text-sm text-red-700">
              缺少微信支付二维码信息，请返回会员价格页重新发起支付。
            </div>
          )}

          <div className="mt-8 flex flex-wrap justify-center gap-3">
            <Link
              href="/orders"
              className="rounded-full bg-cyan-500 px-5 py-3 text-sm font-bold text-white hover:bg-cyan-400"
            >
              查看我的订单
            </Link>
            <Link
              href="/pricing"
              className="rounded-full border border-slate-300 px-5 py-3 text-sm font-bold text-slate-700 hover:border-cyan-400 hover:text-cyan-700"
            >
              返回会员价格
            </Link>
          </div>
        </div>
      </div>
    </main>
  );
}
